# Quarto.yml project file

project:
  type: website
  output-dir: ../docs
  resources:
    - ./data
  render:
    - "*.qmd"

execute:
  echo: false
  kernel: python  # or the name of your Jupyter kernel

website:
  title: "FDA Dashboard"
  navbar:
    left:
      - href: ./index.qmd
        text: Home

format:
  html:
    theme: default
    toc: true
#    smooth-scroll: true
#    code-tools: true
#    # Enable interactive figures
    fig-responsive: true
#    execute:
#      enabled: true
#    embed-resources: true
#    html-math-method: katex
#    plotly: true
    