# Quarto.yml project file

project:
  type: website
  output-dir: ../docs
  render:
    - "*.qmd"

execute:
  echo: false

website:
  title: "The Fan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cleaning.qmd
        text: Cleaning
      - href: dashboard.qmd
        text: Dashboard
      - href: mini_dashboard.qmd
        text: Mini Dashboard

format:
  html:
    html-math-method: katex
    smooth-scroll: true
    embed-resources: true

